version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app           # Mount code & let SQLite write fin.db here
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "sqlite:///./fin.db"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend